% Fill in default parameters for the deep GPIRL algorithm.
function algorithm_params = deepgpirldefaultparams(algorithm_params)

% Create default parameters.
default_params = struct(...
    'seed',0,...
    'all_features',1,...
    'true_features',0,...
    'display_scg2',1,...
    ...% Optional initial values.
    'initial_r',[],...
    'init_r_method','random',...
    'num_init_r',1,...
    ...% Which parameters to learn.
    'warp_x',0,...
    'learn_warp',0,...
    'learn_sigma1',0,...
    'learn_beta1',0,...
    'learn_sigma2',0,...
    'learn_beta2',0,...
    'learn_lambda',0,...
    'learn_Lambda1',0,...
    'learn_Lambda2',0,...
    'learn_EZ',1,...
    'learn_u',1,...
    'SNR_init',50,...
    'Lambda_init',10,...
    'sigma_init',5,...
    'beta_init',1,...
    ...% Parameters for random restarts.
    'gradcheck',0,...
    'num_init',1,...
    ...% These are hyperparameter transformations for positivity constraints.
    'ard_xform','exp',...
    'noise_xform','exp',...
    'rbf_xform','exp',...
    'warp_l_xform','exp',...
    'warp_c_xform','exp',...
    'warp_s_xform','exp',...
    ...% These are hyperparameter priors.
    'ard_prior','logsparsity',...
    'noise_prior','g0',...
    'rbf_prior','none',...
    'warp_l_prior','g0',...
    'warp_c_prior','gamma',...
    'warp_s_prior','g0',...
    'use_num_diff',1,...
    ...% These are prior wights and parameters.
    'ard_prior_wt',1,...
    'noise_prior_wt',1,...
    'rbf_prior_wt',1,...
    'gamma_shape',2,...
    ...% These are initial values.
    'ard_init',1,...
    'noise_init',1e-2,...
    'rbf_init',5,...
    'warp_c_init',2.0,...
    'warp_l_init',1,...
    'warp_s_init',1,...
    ...% These parameters control how the inducing points are selected.
    'inducing_pts','examplesplus',...
    'inducing_pts_count',64,...
    'R',6,...
    'restart_num',5,...
    'restart_iter',100,...
    'max_iter',500);

% Set parameters.
algorithm_params = filldefaultparams(algorithm_params,default_params);
